// This file is generated by omniidl (C++ backend)- omniORB_4_1. Do not edit.

#include "BotArmControlSK.hh"
#include <omniORB4/IOP_S.h>
#include <omniORB4/IOP_C.h>
#include <omniORB4/callDescriptor.h>
#include <omniORB4/callHandle.h>
#include <omniORB4/objTracker.h>


OMNI_USING_NAMESPACE(omni)

static const char* _0RL_library_version = omniORB_4_1;



BotArmControl_ptr BotArmControl_Helper::_nil() {
  return ::BotArmControl::_nil();
}

::CORBA::Boolean BotArmControl_Helper::is_nil(::BotArmControl_ptr p) {
  return ::CORBA::is_nil(p);

}

void BotArmControl_Helper::release(::BotArmControl_ptr p) {
  ::CORBA::release(p);
}

void BotArmControl_Helper::marshalObjRef(::BotArmControl_ptr obj, cdrStream& s) {
  ::BotArmControl::_marshalObjRef(obj, s);
}

BotArmControl_ptr BotArmControl_Helper::unmarshalObjRef(cdrStream& s) {
  return ::BotArmControl::_unmarshalObjRef(s);
}

void BotArmControl_Helper::duplicate(::BotArmControl_ptr obj) {
  if( obj && !obj->_NP_is_nil() )  omni::duplicateObjRef(obj);
}

BotArmControl_ptr
BotArmControl::_duplicate(::BotArmControl_ptr obj)
{
  if( obj && !obj->_NP_is_nil() )  omni::duplicateObjRef(obj);
  return obj;
}

BotArmControl_ptr
BotArmControl::_narrow(::CORBA::Object_ptr obj)
{
  if( !obj || obj->_NP_is_nil() || obj->_NP_is_pseudo() ) return _nil();
  _ptr_type e = (_ptr_type) obj->_PR_getobj()->_realNarrow(_PD_repoId);
  return e ? e : _nil();
}


BotArmControl_ptr
BotArmControl::_unchecked_narrow(::CORBA::Object_ptr obj)
{
  if( !obj || obj->_NP_is_nil() || obj->_NP_is_pseudo() ) return _nil();
  _ptr_type e = (_ptr_type) obj->_PR_getobj()->_uncheckedNarrow(_PD_repoId);
  return e ? e : _nil();
}

BotArmControl_ptr
BotArmControl::_nil()
{
#ifdef OMNI_UNLOADABLE_STUBS
  static _objref_BotArmControl _the_nil_obj;
  return &_the_nil_obj;
#else
  static _objref_BotArmControl* _the_nil_ptr = 0;
  if( !_the_nil_ptr ) {
    omni::nilRefLock().lock();
    if( !_the_nil_ptr ) {
      _the_nil_ptr = new _objref_BotArmControl;
      registerNilCorbaObject(_the_nil_ptr);
    }
    omni::nilRefLock().unlock();
  }
  return _the_nil_ptr;
#endif
}

const char* BotArmControl::_PD_repoId = "IDL:BotArmControl:1.0";


_objref_BotArmControl::~_objref_BotArmControl() {

}


_objref_BotArmControl::_objref_BotArmControl(omniIOR* ior, omniIdentity* id) :
   omniObjRef(::BotArmControl::_PD_repoId, ior, id, 1)


{
  _PR_setobj(this);
}

void*
_objref_BotArmControl::_ptrToObjRef(const char* id)
{
  if( id == ::BotArmControl::_PD_repoId )
    return (::BotArmControl_ptr) this;

  if( id == ::CORBA::Object::_PD_repoId )
    return (::CORBA::Object_ptr) this;

  if( omni::strMatch(id, ::BotArmControl::_PD_repoId) )
    return (::BotArmControl_ptr) this;

  if( omni::strMatch(id, ::CORBA::Object::_PD_repoId) )
    return (::CORBA::Object_ptr) this;

  return 0;
}

// Proxy call descriptor class. Mangled signature:
//  _cshort_i_cshort
class _0RL_cd_26cb7021134ed319_00000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_26cb7021134ed319_00000000(LocalCallFn lcfn,const char* op_,size_t oplen,_CORBA_Boolean upcall=0):
     omniCallDescriptor(lcfn, op_, oplen, 0, 0, 0, upcall)
  {

  }

  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);


  ::CORBA::Short arg_0;
  ::CORBA::Short result;
};

void _0RL_cd_26cb7021134ed319_00000000::marshalArguments(cdrStream& _n)
{
  arg_0 >>= _n;

}

void _0RL_cd_26cb7021134ed319_00000000::unmarshalArguments(cdrStream& _n)
{
  (::CORBA::Short&)arg_0 <<= _n;

}

void _0RL_cd_26cb7021134ed319_00000000::marshalReturnedValues(cdrStream& _n)
{
  result >>= _n;

}

void _0RL_cd_26cb7021134ed319_00000000::unmarshalReturnedValues(cdrStream& _n)
{
  (::CORBA::Short&)result <<= _n;

}

// Local call call-back function.
static void
_0RL_lcfn_26cb7021134ed319_10000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_26cb7021134ed319_00000000* tcd = (_0RL_cd_26cb7021134ed319_00000000*)cd;
  _impl_BotArmControl* impl = (_impl_BotArmControl*) svnt->_ptrToInterface(BotArmControl::_PD_repoId);
  tcd->result = impl->getEncoder(tcd->arg_0);


}

::CORBA::Short _objref_BotArmControl::getEncoder(::CORBA::Short motor)
{
  _0RL_cd_26cb7021134ed319_00000000 _call_desc(_0RL_lcfn_26cb7021134ed319_10000000, "getEncoder", 11);
  _call_desc.arg_0 = motor;

  _invoke(_call_desc);
  return _call_desc.result;


}
// Proxy call descriptor class. Mangled signature:
//  void_i_cshort_i_cfloat
class _0RL_cd_26cb7021134ed319_20000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_26cb7021134ed319_20000000(LocalCallFn lcfn,const char* op_,size_t oplen,_CORBA_Boolean upcall=0):
     omniCallDescriptor(lcfn, op_, oplen, 0, 0, 0, upcall)
  {

  }

  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);



  ::CORBA::Short arg_0;
  ::CORBA::Float arg_1;
};

void _0RL_cd_26cb7021134ed319_20000000::marshalArguments(cdrStream& _n)
{
  arg_0 >>= _n;
  arg_1 >>= _n;

}

void _0RL_cd_26cb7021134ed319_20000000::unmarshalArguments(cdrStream& _n)
{
  (::CORBA::Short&)arg_0 <<= _n;
  (::CORBA::Float&)arg_1 <<= _n;

}

// Local call call-back function.
static void
_0RL_lcfn_26cb7021134ed319_30000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_26cb7021134ed319_20000000* tcd = (_0RL_cd_26cb7021134ed319_20000000*)cd;
  _impl_BotArmControl* impl = (_impl_BotArmControl*) svnt->_ptrToInterface(BotArmControl::_PD_repoId);
  impl->setMotor(tcd->arg_0, tcd->arg_1);


}

void _objref_BotArmControl::setMotor(::CORBA::Short i, ::CORBA::Float val)
{
  _0RL_cd_26cb7021134ed319_20000000 _call_desc(_0RL_lcfn_26cb7021134ed319_30000000, "setMotor", 9);
  _call_desc.arg_0 = i;
  _call_desc.arg_1 = val;

  _invoke(_call_desc);



}
// Proxy call descriptor class. Mangled signature:
//  void
class _0RL_cd_26cb7021134ed319_40000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_26cb7021134ed319_40000000(LocalCallFn lcfn,const char* op_,size_t oplen,_CORBA_Boolean upcall=0):
     omniCallDescriptor(lcfn, op_, oplen, 0, 0, 0, upcall)
  {

  }





};

// Local call call-back function.
static void
_0RL_lcfn_26cb7021134ed319_50000000(omniCallDescriptor*, omniServant* svnt)
{

  _impl_BotArmControl* impl = (_impl_BotArmControl*) svnt->_ptrToInterface(BotArmControl::_PD_repoId);
  impl->shutdown();


}

void _objref_BotArmControl::shutdown()
{
  _0RL_cd_26cb7021134ed319_40000000 _call_desc(_0RL_lcfn_26cb7021134ed319_50000000, "shutdown", 9);


  _invoke(_call_desc);



}
_pof_BotArmControl::~_pof_BotArmControl() {}


omniObjRef*
_pof_BotArmControl::newObjRef(omniIOR* ior, omniIdentity* id)
{
  return new ::_objref_BotArmControl(ior, id);
}


::CORBA::Boolean
_pof_BotArmControl::is_a(const char* id) const
{
  if( omni::ptrStrMatch(id, ::BotArmControl::_PD_repoId) )
    return 1;

  return 0;
}

const _pof_BotArmControl _the_pof_BotArmControl;

_impl_BotArmControl::~_impl_BotArmControl() {}


::CORBA::Boolean
_impl_BotArmControl::_dispatch(omniCallHandle& _handle)
{
  const char* op = _handle.operation_name();

  if( omni::strMatch(op, "getEncoder") ) {

    _0RL_cd_26cb7021134ed319_00000000 _call_desc(_0RL_lcfn_26cb7021134ed319_10000000, "getEncoder", 11, 1);

    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "setMotor") ) {

    _0RL_cd_26cb7021134ed319_20000000 _call_desc(_0RL_lcfn_26cb7021134ed319_30000000, "setMotor", 9, 1);

    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "shutdown") ) {

    _0RL_cd_26cb7021134ed319_40000000 _call_desc(_0RL_lcfn_26cb7021134ed319_50000000, "shutdown", 9, 1);

    _handle.upcall(this,_call_desc);
    return 1;
  }


  return 0;
}

void*
_impl_BotArmControl::_ptrToInterface(const char* id)
{
  if( id == ::BotArmControl::_PD_repoId )
    return (::_impl_BotArmControl*) this;

  if( id == ::CORBA::Object::_PD_repoId )
    return (void*) 1;

  if( omni::strMatch(id, ::BotArmControl::_PD_repoId) )
    return (::_impl_BotArmControl*) this;

  if( omni::strMatch(id, ::CORBA::Object::_PD_repoId) )
    return (void*) 1;
  return 0;
}

const char*
_impl_BotArmControl::_mostDerivedRepoId()
{
  return ::BotArmControl::_PD_repoId;
}

POA_BotArmControl::~POA_BotArmControl() {}

