/*!@file Corba/Objects/BotControlServer.idl idl file for BotControl object */

//////////////////////////////////////////////////////////////////// //
// The iLab Neuromorphic Vision C++ Toolkit - Copyright (C) 2001 by the //
// University of Southern California (USC) and the iLab at USC.         //
// See http://iLab.usc.edu for information about this project.          //
// //////////////////////////////////////////////////////////////////// //
// Major portions of the iLab Neuromorphic Vision Toolkit are protected //
// under the U.S. patent ``Computation of Intrinsic Perceptual Saliency //
// in Visual Environments, and Applications'' by Christof Koch and      //
// Laurent Itti, California Institute of Technology, 2001 (patent       //
// pending; application number 09/912,225 filed July 23, 2001; see      //
// http://pair.uspto.gov/cgi-bin/final/home.pl for current status).     //
// //////////////////////////////////////////////////////////////////// //
// This file is part of the iLab Neuromorphic Vision C++ Toolkit.       //
//                                                                      //
// The iLab Neuromorphic Vision C++ Toolkit is free software; you can   //
// redistribute it and/or modify it under the terms of the GNU General  //
// Public License as published by the Free Software Foundation; either  //
// version 2 of the License, or (at your option) any later version.     //
//                                                                      //
// The iLab Neuromorphic Vision C++ Toolkit is distributed in the hope  //
// that it will be useful, but WITHOUT ANY WARRANTY; without even the   //
// implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR      //
// PURPOSE.  See the GNU General Public License for more details.       //
//                                                                      //
// You should have received a copy of the GNU General Public License    //
// along with the iLab Neuromorphic Vision C++ Toolkit; if not, write   //
// to the Free Software Foundation, Inc., 59 Temple Place, Suite 330,   //
// Boston, MA 02111-1307 USA.                                           //
// //////////////////////////////////////////////////////////////////// //
//
// Primary maintainer for this file: Lior Elazary <lelazary@yahoo.com>
// $HeadURL$
// $Id$
//

#include "Corba/ImageOrb.idl"

interface BotControlServer {

	//! Init process 
	void init();
	//!set the speed -1.0 (reverse) ... 1.0 (forward)
	float getSpeed();
	//!get the speed -1.0 ... 1.0
	short setSpeed(in float speed);

  //! gets steering angle; input from -1.0 (full left) to 1.0 (full right)
  float getSteering();
  //! sets steering angle; input from -1.0 (full left) to 1.0 (full right)
  short setSteering(in float steeringPos);

	//! gets the image sensor i
	ImageOrb getImageSensor(in short i); 

	//! Get image sersor dims
	void getImageSensorDims(out short w, out short h, in short i);

	//! set the info for the disp
	void setInfo(in string info, in Point2DOrb trackLoc, in Point2DOrb recLoc);

	//! Get the user input
	short getUserInput(out Point2DOrb loc);


	// Shuts down the server
	void shutdown();
};

