// This file is generated by omniidl (C++ backend)- omniORB_4_1. Do not edit.
#ifndef __BotControlServer_hh__
#define __BotControlServer_hh__

#ifndef __CORBA_H_EXTERNAL_GUARD__
#include <omniORB4/CORBA.h>
#endif

#ifndef  USE_stub_in_nt_dll
# define USE_stub_in_nt_dll_NOT_DEFINED_BotControlServer
#endif
#ifndef  USE_core_stub_in_nt_dll
# define USE_core_stub_in_nt_dll_NOT_DEFINED_BotControlServer
#endif
#ifndef  USE_dyn_stub_in_nt_dll
# define USE_dyn_stub_in_nt_dll_NOT_DEFINED_BotControlServer
#endif



#ifndef __ImageOrb_hh_EXTERNAL_GUARD__
#define __ImageOrb_hh_EXTERNAL_GUARD__
#include "Corba/ImageOrbSK.hh"
#endif



#ifdef USE_stub_in_nt_dll
# ifndef USE_core_stub_in_nt_dll
#  define USE_core_stub_in_nt_dll
# endif
# ifndef USE_dyn_stub_in_nt_dll
#  define USE_dyn_stub_in_nt_dll
# endif
#endif

#ifdef _core_attr
# error "A local CPP macro _core_attr has already been defined."
#else
# ifdef  USE_core_stub_in_nt_dll
#  define _core_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _core_attr
# endif
#endif

#ifdef _dyn_attr
# error "A local CPP macro _dyn_attr has already been defined."
#else
# ifdef  USE_dyn_stub_in_nt_dll
#  define _dyn_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _dyn_attr
# endif
#endif





#ifndef __BotControlServer__
#define __BotControlServer__

class BotControlServer;
class _objref_BotControlServer;
class _impl_BotControlServer;

typedef _objref_BotControlServer* BotControlServer_ptr;
typedef BotControlServer_ptr BotControlServerRef;

class BotControlServer_Helper {
public:
  typedef BotControlServer_ptr _ptr_type;

  static _ptr_type _nil();
  static _CORBA_Boolean is_nil(_ptr_type);
  static void release(_ptr_type);
  static void duplicate(_ptr_type);
  static void marshalObjRef(_ptr_type, cdrStream&);
  static _ptr_type unmarshalObjRef(cdrStream&);
};

typedef _CORBA_ObjRef_Var<_objref_BotControlServer, BotControlServer_Helper> BotControlServer_var;
typedef _CORBA_ObjRef_OUT_arg<_objref_BotControlServer,BotControlServer_Helper > BotControlServer_out;

#endif

// interface BotControlServer
class BotControlServer {
public:
  // Declarations for this interface type.
  typedef BotControlServer_ptr _ptr_type;
  typedef BotControlServer_var _var_type;

  static _ptr_type _duplicate(_ptr_type);
  static _ptr_type _narrow(::CORBA::Object_ptr);
  static _ptr_type _unchecked_narrow(::CORBA::Object_ptr);

  static _ptr_type _nil();

  static inline void _marshalObjRef(_ptr_type, cdrStream&);

  static inline _ptr_type _unmarshalObjRef(cdrStream& s) {
    omniObjRef* o = omniObjRef::_unMarshal(_PD_repoId,s);
    if (o)
      return (_ptr_type) o->_ptrToObjRef(_PD_repoId);
    else
      return _nil();
  }

  static _core_attr const char* _PD_repoId;

  // Other IDL defined within this scope.

};

class _objref_BotControlServer :
  public virtual ::CORBA::Object,
  public virtual omniObjRef
{
public:
  void init();
  ::CORBA::Float getSpeed();
  ::CORBA::Short setSpeed(::CORBA::Float speed);
  ::CORBA::Float getSteering();
  ::CORBA::Short setSteering(::CORBA::Float steeringPos);
  ImageOrb* getImageSensor(::CORBA::Short i);
  void getImageSensorDims(::CORBA::Short& w, ::CORBA::Short& h, ::CORBA::Short i);
  void setInfo(const char* info, const Point2DOrb& trackLoc, const Point2DOrb& recLoc);
  ::CORBA::Short getUserInput(Point2DOrb& loc);
  void shutdown();

  inline _objref_BotControlServer()  { _PR_setobj(0); }  // nil
  _objref_BotControlServer(omniIOR*, omniIdentity*);

protected:
  virtual ~_objref_BotControlServer();


private:
  virtual void* _ptrToObjRef(const char*);

  _objref_BotControlServer(const _objref_BotControlServer&);
  _objref_BotControlServer& operator = (const _objref_BotControlServer&);
  // not implemented

  friend class BotControlServer;
};

class _pof_BotControlServer : public _OMNI_NS(proxyObjectFactory) {
public:
  inline _pof_BotControlServer() : _OMNI_NS(proxyObjectFactory)(BotControlServer::_PD_repoId) {}
  virtual ~_pof_BotControlServer();

  virtual omniObjRef* newObjRef(omniIOR*,omniIdentity*);
  virtual _CORBA_Boolean is_a(const char*) const;
};

class _impl_BotControlServer :
  public virtual omniServant
{
public:
  virtual ~_impl_BotControlServer();

  virtual void init() = 0;
  virtual ::CORBA::Float getSpeed() = 0;
  virtual ::CORBA::Short setSpeed(::CORBA::Float speed) = 0;
  virtual ::CORBA::Float getSteering() = 0;
  virtual ::CORBA::Short setSteering(::CORBA::Float steeringPos) = 0;
  virtual ImageOrb* getImageSensor(::CORBA::Short i) = 0;
  virtual void getImageSensorDims(::CORBA::Short& w, ::CORBA::Short& h, ::CORBA::Short i) = 0;
  virtual void setInfo(const char* info, const Point2DOrb& trackLoc, const Point2DOrb& recLoc) = 0;
  virtual ::CORBA::Short getUserInput(Point2DOrb& loc) = 0;
  virtual void shutdown() = 0;

public:  // Really protected, workaround for xlC
  virtual _CORBA_Boolean _dispatch(omniCallHandle&);

private:
  virtual void* _ptrToInterface(const char*);
  virtual const char* _mostDerivedRepoId();

};




class POA_BotControlServer :
  public virtual _impl_BotControlServer,
  public virtual ::PortableServer::ServantBase
{
public:
  virtual ~POA_BotControlServer();

  inline ::BotControlServer_ptr _this() {
    return (::BotControlServer_ptr) _do_this(::BotControlServer::_PD_repoId);
  }
};







#undef _core_attr
#undef _dyn_attr



inline void
BotControlServer::_marshalObjRef(::BotControlServer_ptr obj, cdrStream& s) {
  omniObjRef::_marshal(obj->_PR_getobj(),s);
}




#ifdef   USE_stub_in_nt_dll_NOT_DEFINED_BotControlServer
# undef  USE_stub_in_nt_dll
# undef  USE_stub_in_nt_dll_NOT_DEFINED_BotControlServer
#endif
#ifdef   USE_core_stub_in_nt_dll_NOT_DEFINED_BotControlServer
# undef  USE_core_stub_in_nt_dll
# undef  USE_core_stub_in_nt_dll_NOT_DEFINED_BotControlServer
#endif
#ifdef   USE_dyn_stub_in_nt_dll_NOT_DEFINED_BotControlServer
# undef  USE_dyn_stub_in_nt_dll
# undef  USE_dyn_stub_in_nt_dll_NOT_DEFINED_BotControlServer
#endif

#endif  // __BotControlServer_hh__

