// This file is generated by omniidl (C++ backend)- omniORB_4_1. Do not edit.

#include "BotControlSK.hh"
#include <omniORB4/IOP_S.h>
#include <omniORB4/IOP_C.h>
#include <omniORB4/callDescriptor.h>
#include <omniORB4/callHandle.h>
#include <omniORB4/objTracker.h>


OMNI_USING_NAMESPACE(omni)

static const char* _0RL_library_version = omniORB_4_1;



BotControl_ptr BotControl_Helper::_nil() {
  return ::BotControl::_nil();
}

::CORBA::Boolean BotControl_Helper::is_nil(::BotControl_ptr p) {
  return ::CORBA::is_nil(p);

}

void BotControl_Helper::release(::BotControl_ptr p) {
  ::CORBA::release(p);
}

void BotControl_Helper::marshalObjRef(::BotControl_ptr obj, cdrStream& s) {
  ::BotControl::_marshalObjRef(obj, s);
}

BotControl_ptr BotControl_Helper::unmarshalObjRef(cdrStream& s) {
  return ::BotControl::_unmarshalObjRef(s);
}

void BotControl_Helper::duplicate(::BotControl_ptr obj) {
  if( obj && !obj->_NP_is_nil() )  omni::duplicateObjRef(obj);
}

BotControl_ptr
BotControl::_duplicate(::BotControl_ptr obj)
{
  if( obj && !obj->_NP_is_nil() )  omni::duplicateObjRef(obj);
  return obj;
}

BotControl_ptr
BotControl::_narrow(::CORBA::Object_ptr obj)
{
  if( !obj || obj->_NP_is_nil() || obj->_NP_is_pseudo() ) return _nil();
  _ptr_type e = (_ptr_type) obj->_PR_getobj()->_realNarrow(_PD_repoId);
  return e ? e : _nil();
}


BotControl_ptr
BotControl::_unchecked_narrow(::CORBA::Object_ptr obj)
{
  if( !obj || obj->_NP_is_nil() || obj->_NP_is_pseudo() ) return _nil();
  _ptr_type e = (_ptr_type) obj->_PR_getobj()->_uncheckedNarrow(_PD_repoId);
  return e ? e : _nil();
}

BotControl_ptr
BotControl::_nil()
{
#ifdef OMNI_UNLOADABLE_STUBS
  static _objref_BotControl _the_nil_obj;
  return &_the_nil_obj;
#else
  static _objref_BotControl* _the_nil_ptr = 0;
  if( !_the_nil_ptr ) {
    omni::nilRefLock().lock();
    if( !_the_nil_ptr ) {
      _the_nil_ptr = new _objref_BotControl;
      registerNilCorbaObject(_the_nil_ptr);
    }
    omni::nilRefLock().unlock();
  }
  return _the_nil_ptr;
#endif
}

const char* BotControl::_PD_repoId = "IDL:BotControl:1.0";


_objref_BotControl::~_objref_BotControl() {

}


_objref_BotControl::_objref_BotControl(omniIOR* ior, omniIdentity* id) :
   omniObjRef(::BotControl::_PD_repoId, ior, id, 1)


{
  _PR_setobj(this);
}

void*
_objref_BotControl::_ptrToObjRef(const char* id)
{
  if( id == ::BotControl::_PD_repoId )
    return (::BotControl_ptr) this;

  if( id == ::CORBA::Object::_PD_repoId )
    return (::CORBA::Object_ptr) this;

  if( omni::strMatch(id, ::BotControl::_PD_repoId) )
    return (::BotControl_ptr) this;

  if( omni::strMatch(id, ::CORBA::Object::_PD_repoId) )
    return (::CORBA::Object_ptr) this;

  return 0;
}

// Proxy call descriptor class. Mangled signature:
//  void
class _0RL_cd_1473fd27e4f46097_00000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_1473fd27e4f46097_00000000(LocalCallFn lcfn,const char* op_,size_t oplen,_CORBA_Boolean upcall=0):
     omniCallDescriptor(lcfn, op_, oplen, 0, 0, 0, upcall)
  {

  }





};

// Local call call-back function.
static void
_0RL_lcfn_1473fd27e4f46097_10000000(omniCallDescriptor*, omniServant* svnt)
{

  _impl_BotControl* impl = (_impl_BotControl*) svnt->_ptrToInterface(BotControl::_PD_repoId);
  impl->init();


}

void _objref_BotControl::init()
{
  _0RL_cd_1473fd27e4f46097_00000000 _call_desc(_0RL_lcfn_1473fd27e4f46097_10000000, "init", 5);


  _invoke(_call_desc);



}
// Proxy call descriptor class. Mangled signature:
//  _cfloat
class _0RL_cd_1473fd27e4f46097_20000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_1473fd27e4f46097_20000000(LocalCallFn lcfn,const char* op_,size_t oplen,_CORBA_Boolean upcall=0):
     omniCallDescriptor(lcfn, op_, oplen, 0, 0, 0, upcall)
  {

  }


  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);


  ::CORBA::Float result;
};

void _0RL_cd_1473fd27e4f46097_20000000::marshalReturnedValues(cdrStream& _n)
{
  result >>= _n;

}

void _0RL_cd_1473fd27e4f46097_20000000::unmarshalReturnedValues(cdrStream& _n)
{
  (::CORBA::Float&)result <<= _n;

}

// Local call call-back function.
static void
_0RL_lcfn_1473fd27e4f46097_30000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_1473fd27e4f46097_20000000* tcd = (_0RL_cd_1473fd27e4f46097_20000000*)cd;
  _impl_BotControl* impl = (_impl_BotControl*) svnt->_ptrToInterface(BotControl::_PD_repoId);
  tcd->result = impl->getSpeed();


}

::CORBA::Float _objref_BotControl::getSpeed()
{
  _0RL_cd_1473fd27e4f46097_20000000 _call_desc(_0RL_lcfn_1473fd27e4f46097_30000000, "getSpeed", 9);


  _invoke(_call_desc);
  return _call_desc.result;


}
// Proxy call descriptor class. Mangled signature:
//  _cshort_i_cfloat
class _0RL_cd_1473fd27e4f46097_40000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_1473fd27e4f46097_40000000(LocalCallFn lcfn,const char* op_,size_t oplen,_CORBA_Boolean upcall=0):
     omniCallDescriptor(lcfn, op_, oplen, 0, 0, 0, upcall)
  {

  }

  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);


  ::CORBA::Float arg_0;
  ::CORBA::Short result;
};

void _0RL_cd_1473fd27e4f46097_40000000::marshalArguments(cdrStream& _n)
{
  arg_0 >>= _n;

}

void _0RL_cd_1473fd27e4f46097_40000000::unmarshalArguments(cdrStream& _n)
{
  (::CORBA::Float&)arg_0 <<= _n;

}

void _0RL_cd_1473fd27e4f46097_40000000::marshalReturnedValues(cdrStream& _n)
{
  result >>= _n;

}

void _0RL_cd_1473fd27e4f46097_40000000::unmarshalReturnedValues(cdrStream& _n)
{
  (::CORBA::Short&)result <<= _n;

}

// Local call call-back function.
static void
_0RL_lcfn_1473fd27e4f46097_50000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_1473fd27e4f46097_40000000* tcd = (_0RL_cd_1473fd27e4f46097_40000000*)cd;
  _impl_BotControl* impl = (_impl_BotControl*) svnt->_ptrToInterface(BotControl::_PD_repoId);
  tcd->result = impl->setSpeed(tcd->arg_0);


}

::CORBA::Short _objref_BotControl::setSpeed(::CORBA::Float speed)
{
  _0RL_cd_1473fd27e4f46097_40000000 _call_desc(_0RL_lcfn_1473fd27e4f46097_50000000, "setSpeed", 9);
  _call_desc.arg_0 = speed;

  _invoke(_call_desc);
  return _call_desc.result;


}
// Local call call-back function.
static void
_0RL_lcfn_1473fd27e4f46097_60000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_1473fd27e4f46097_20000000* tcd = (_0RL_cd_1473fd27e4f46097_20000000*)cd;
  _impl_BotControl* impl = (_impl_BotControl*) svnt->_ptrToInterface(BotControl::_PD_repoId);
  tcd->result = impl->getSteering();


}

::CORBA::Float _objref_BotControl::getSteering()
{
  _0RL_cd_1473fd27e4f46097_20000000 _call_desc(_0RL_lcfn_1473fd27e4f46097_60000000, "getSteering", 12);


  _invoke(_call_desc);
  return _call_desc.result;


}
// Local call call-back function.
static void
_0RL_lcfn_1473fd27e4f46097_70000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_1473fd27e4f46097_40000000* tcd = (_0RL_cd_1473fd27e4f46097_40000000*)cd;
  _impl_BotControl* impl = (_impl_BotControl*) svnt->_ptrToInterface(BotControl::_PD_repoId);
  tcd->result = impl->setSteering(tcd->arg_0);


}

::CORBA::Short _objref_BotControl::setSteering(::CORBA::Float steeringPos)
{
  _0RL_cd_1473fd27e4f46097_40000000 _call_desc(_0RL_lcfn_1473fd27e4f46097_70000000, "setSteering", 12);
  _call_desc.arg_0 = steeringPos;

  _invoke(_call_desc);
  return _call_desc.result;


}
// Proxy call descriptor class. Mangled signature:
//  _cImageOrb_i_cshort
class _0RL_cd_1473fd27e4f46097_80000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_1473fd27e4f46097_80000000(LocalCallFn lcfn,const char* op_,size_t oplen,_CORBA_Boolean upcall=0):
     omniCallDescriptor(lcfn, op_, oplen, 0, 0, 0, upcall)
  {

  }

  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);


  ::CORBA::Short arg_0;
  ImageOrb_var result;
};

void _0RL_cd_1473fd27e4f46097_80000000::marshalArguments(cdrStream& _n)
{
  arg_0 >>= _n;

}

void _0RL_cd_1473fd27e4f46097_80000000::unmarshalArguments(cdrStream& _n)
{
  (::CORBA::Short&)arg_0 <<= _n;

}

void _0RL_cd_1473fd27e4f46097_80000000::marshalReturnedValues(cdrStream& _n)
{
  (const ImageOrb&) result >>= _n;

}

void _0RL_cd_1473fd27e4f46097_80000000::unmarshalReturnedValues(cdrStream& _n)
{
  result = new ImageOrb;
  (ImageOrb&)result <<= _n;

}

// Local call call-back function.
static void
_0RL_lcfn_1473fd27e4f46097_90000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_1473fd27e4f46097_80000000* tcd = (_0RL_cd_1473fd27e4f46097_80000000*)cd;
  _impl_BotControl* impl = (_impl_BotControl*) svnt->_ptrToInterface(BotControl::_PD_repoId);
  tcd->result = impl->getImageSensor(tcd->arg_0);


}

ImageOrb* _objref_BotControl::getImageSensor(::CORBA::Short i)
{
  _0RL_cd_1473fd27e4f46097_80000000 _call_desc(_0RL_lcfn_1473fd27e4f46097_90000000, "getImageSensor", 15);
  _call_desc.arg_0 = i;

  _invoke(_call_desc);
  return _call_desc.result._retn();


}
// Proxy call descriptor class. Mangled signature:
//  void_o_cshort_o_cshort_i_cshort
class _0RL_cd_1473fd27e4f46097_a0000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_1473fd27e4f46097_a0000000(LocalCallFn lcfn,const char* op_,size_t oplen,_CORBA_Boolean upcall=0):
     omniCallDescriptor(lcfn, op_, oplen, 0, 0, 0, upcall)
  {

  }

  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);


  ::CORBA::Short arg_0;
  ::CORBA::Short arg_1;
  ::CORBA::Short arg_2;
};

void _0RL_cd_1473fd27e4f46097_a0000000::marshalArguments(cdrStream& _n)
{
  arg_2 >>= _n;

}

void _0RL_cd_1473fd27e4f46097_a0000000::unmarshalArguments(cdrStream& _n)
{
  (::CORBA::Short&)arg_2 <<= _n;

}

void _0RL_cd_1473fd27e4f46097_a0000000::marshalReturnedValues(cdrStream& _n)
{
  arg_0 >>= _n;
  arg_1 >>= _n;

}

void _0RL_cd_1473fd27e4f46097_a0000000::unmarshalReturnedValues(cdrStream& _n)
{
  (::CORBA::Short&)arg_0 <<= _n;
  (::CORBA::Short&)arg_1 <<= _n;

}

// Local call call-back function.
static void
_0RL_lcfn_1473fd27e4f46097_b0000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_1473fd27e4f46097_a0000000* tcd = (_0RL_cd_1473fd27e4f46097_a0000000*)cd;
  _impl_BotControl* impl = (_impl_BotControl*) svnt->_ptrToInterface(BotControl::_PD_repoId);
  impl->getImageSensorDims(tcd->arg_0, tcd->arg_1, tcd->arg_2);


}

void _objref_BotControl::getImageSensorDims(::CORBA::Short& w, ::CORBA::Short& h, ::CORBA::Short i)
{
  _0RL_cd_1473fd27e4f46097_a0000000 _call_desc(_0RL_lcfn_1473fd27e4f46097_b0000000, "getImageSensorDims", 19);
  _call_desc.arg_2 = i;

  _invoke(_call_desc);
  w = _call_desc.arg_0;
  h = _call_desc.arg_1;


}
// Proxy call descriptor class. Mangled signature:
//  _cshort_i_cshort
class _0RL_cd_1473fd27e4f46097_c0000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_1473fd27e4f46097_c0000000(LocalCallFn lcfn,const char* op_,size_t oplen,_CORBA_Boolean upcall=0):
     omniCallDescriptor(lcfn, op_, oplen, 0, 0, 0, upcall)
  {

  }

  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);


  ::CORBA::Short arg_0;
  ::CORBA::Short result;
};

void _0RL_cd_1473fd27e4f46097_c0000000::marshalArguments(cdrStream& _n)
{
  arg_0 >>= _n;

}

void _0RL_cd_1473fd27e4f46097_c0000000::unmarshalArguments(cdrStream& _n)
{
  (::CORBA::Short&)arg_0 <<= _n;

}

void _0RL_cd_1473fd27e4f46097_c0000000::marshalReturnedValues(cdrStream& _n)
{
  result >>= _n;

}

void _0RL_cd_1473fd27e4f46097_c0000000::unmarshalReturnedValues(cdrStream& _n)
{
  (::CORBA::Short&)result <<= _n;

}

// Local call call-back function.
static void
_0RL_lcfn_1473fd27e4f46097_d0000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_1473fd27e4f46097_c0000000* tcd = (_0RL_cd_1473fd27e4f46097_c0000000*)cd;
  _impl_BotControl* impl = (_impl_BotControl*) svnt->_ptrToInterface(BotControl::_PD_repoId);
  tcd->result = impl->getSensorValue(tcd->arg_0);


}

::CORBA::Short _objref_BotControl::getSensorValue(::CORBA::Short i)
{
  _0RL_cd_1473fd27e4f46097_c0000000 _call_desc(_0RL_lcfn_1473fd27e4f46097_d0000000, "getSensorValue", 15);
  _call_desc.arg_0 = i;

  _invoke(_call_desc);
  return _call_desc.result;


}
// Proxy call descriptor class. Mangled signature:
//  void_i_cshort
class _0RL_cd_1473fd27e4f46097_e0000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_1473fd27e4f46097_e0000000(LocalCallFn lcfn,const char* op_,size_t oplen,_CORBA_Boolean upcall=0):
     omniCallDescriptor(lcfn, op_, oplen, 0, 0, 0, upcall)
  {

  }

  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);



  ::CORBA::Short arg_0;
};

void _0RL_cd_1473fd27e4f46097_e0000000::marshalArguments(cdrStream& _n)
{
  arg_0 >>= _n;

}

void _0RL_cd_1473fd27e4f46097_e0000000::unmarshalArguments(cdrStream& _n)
{
  (::CORBA::Short&)arg_0 <<= _n;

}

// Local call call-back function.
static void
_0RL_lcfn_1473fd27e4f46097_f0000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_1473fd27e4f46097_e0000000* tcd = (_0RL_cd_1473fd27e4f46097_e0000000*)cd;
  _impl_BotControl* impl = (_impl_BotControl*) svnt->_ptrToInterface(BotControl::_PD_repoId);
  impl->motorsOff(tcd->arg_0);


}

void _objref_BotControl::motorsOff(::CORBA::Short i)
{
  _0RL_cd_1473fd27e4f46097_e0000000 _call_desc(_0RL_lcfn_1473fd27e4f46097_f0000000, "motorsOff", 10);
  _call_desc.arg_0 = i;

  _invoke(_call_desc);



}
// Proxy call descriptor class. Mangled signature:
//  void_i_cshort_i_cfloat
class _0RL_cd_1473fd27e4f46097_01000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_1473fd27e4f46097_01000000(LocalCallFn lcfn,const char* op_,size_t oplen,_CORBA_Boolean upcall=0):
     omniCallDescriptor(lcfn, op_, oplen, 0, 0, 0, upcall)
  {

  }

  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);



  ::CORBA::Short arg_0;
  ::CORBA::Float arg_1;
};

void _0RL_cd_1473fd27e4f46097_01000000::marshalArguments(cdrStream& _n)
{
  arg_0 >>= _n;
  arg_1 >>= _n;

}

void _0RL_cd_1473fd27e4f46097_01000000::unmarshalArguments(cdrStream& _n)
{
  (::CORBA::Short&)arg_0 <<= _n;
  (::CORBA::Float&)arg_1 <<= _n;

}

// Local call call-back function.
static void
_0RL_lcfn_1473fd27e4f46097_11000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_1473fd27e4f46097_01000000* tcd = (_0RL_cd_1473fd27e4f46097_01000000*)cd;
  _impl_BotControl* impl = (_impl_BotControl*) svnt->_ptrToInterface(BotControl::_PD_repoId);
  impl->setMotor(tcd->arg_0, tcd->arg_1);


}

void _objref_BotControl::setMotor(::CORBA::Short i, ::CORBA::Float val)
{
  _0RL_cd_1473fd27e4f46097_01000000 _call_desc(_0RL_lcfn_1473fd27e4f46097_11000000, "setMotor", 9);
  _call_desc.arg_0 = i;
  _call_desc.arg_1 = val;

  _invoke(_call_desc);



}
// Proxy call descriptor class. Mangled signature:
//  _cshort_i_cCmdData
class _0RL_cd_1473fd27e4f46097_21000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_1473fd27e4f46097_21000000(LocalCallFn lcfn,const char* op_,size_t oplen,_CORBA_Boolean upcall=0):
     omniCallDescriptor(lcfn, op_, oplen, 0, 0, 0, upcall)
  {

  }

  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);


  CmdData_var arg_0_;
  const CmdData* arg_0;
  ::CORBA::Short result;
};

void _0RL_cd_1473fd27e4f46097_21000000::marshalArguments(cdrStream& _n)
{
  (const CmdData&) *arg_0 >>= _n;

}

void _0RL_cd_1473fd27e4f46097_21000000::unmarshalArguments(cdrStream& _n)
{
  arg_0_ = new CmdData;
  (CmdData&)arg_0_ <<= _n;
  arg_0 = &arg_0_.in();

}

void _0RL_cd_1473fd27e4f46097_21000000::marshalReturnedValues(cdrStream& _n)
{
  result >>= _n;

}

void _0RL_cd_1473fd27e4f46097_21000000::unmarshalReturnedValues(cdrStream& _n)
{
  (::CORBA::Short&)result <<= _n;

}

// Local call call-back function.
static void
_0RL_lcfn_1473fd27e4f46097_31000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_1473fd27e4f46097_21000000* tcd = (_0RL_cd_1473fd27e4f46097_21000000*)cd;
  _impl_BotControl* impl = (_impl_BotControl*) svnt->_ptrToInterface(BotControl::_PD_repoId);
  tcd->result = impl->sendRawCmd(*tcd->arg_0);


}

::CORBA::Short _objref_BotControl::sendRawCmd(const CmdData& data)
{
  _0RL_cd_1473fd27e4f46097_21000000 _call_desc(_0RL_lcfn_1473fd27e4f46097_31000000, "sendRawCmd", 11);
  _call_desc.arg_0 = &(CmdData&) data;

  _invoke(_call_desc);
  return _call_desc.result;


}
// Local call call-back function.
static void
_0RL_lcfn_1473fd27e4f46097_41000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_1473fd27e4f46097_e0000000* tcd = (_0RL_cd_1473fd27e4f46097_e0000000*)cd;
  _impl_BotControl* impl = (_impl_BotControl*) svnt->_ptrToInterface(BotControl::_PD_repoId);
  impl->setOIMode(tcd->arg_0);


}

void _objref_BotControl::setOIMode(::CORBA::Short m)
{
  _0RL_cd_1473fd27e4f46097_e0000000 _call_desc(_0RL_lcfn_1473fd27e4f46097_41000000, "setOIMode", 10);
  _call_desc.arg_0 = m;

  _invoke(_call_desc);



}
// Local call call-back function.
static void
_0RL_lcfn_1473fd27e4f46097_51000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_1473fd27e4f46097_e0000000* tcd = (_0RL_cd_1473fd27e4f46097_e0000000*)cd;
  _impl_BotControl* impl = (_impl_BotControl*) svnt->_ptrToInterface(BotControl::_PD_repoId);
  impl->playSong(tcd->arg_0);


}

void _objref_BotControl::playSong(::CORBA::Short song)
{
  _0RL_cd_1473fd27e4f46097_e0000000 _call_desc(_0RL_lcfn_1473fd27e4f46097_51000000, "playSong", 9);
  _call_desc.arg_0 = song;

  _invoke(_call_desc);



}
// Local call call-back function.
static void
_0RL_lcfn_1473fd27e4f46097_61000000(omniCallDescriptor*, omniServant* svnt)
{

  _impl_BotControl* impl = (_impl_BotControl*) svnt->_ptrToInterface(BotControl::_PD_repoId);
  impl->dock();


}

void _objref_BotControl::dock()
{
  _0RL_cd_1473fd27e4f46097_00000000 _call_desc(_0RL_lcfn_1473fd27e4f46097_61000000, "dock", 5);


  _invoke(_call_desc);



}
// Local call call-back function.
static void
_0RL_lcfn_1473fd27e4f46097_71000000(omniCallDescriptor*, omniServant* svnt)
{

  _impl_BotControl* impl = (_impl_BotControl*) svnt->_ptrToInterface(BotControl::_PD_repoId);
  impl->shutdown();


}

void _objref_BotControl::shutdown()
{
  _0RL_cd_1473fd27e4f46097_00000000 _call_desc(_0RL_lcfn_1473fd27e4f46097_71000000, "shutdown", 9);


  _invoke(_call_desc);



}
_pof_BotControl::~_pof_BotControl() {}


omniObjRef*
_pof_BotControl::newObjRef(omniIOR* ior, omniIdentity* id)
{
  return new ::_objref_BotControl(ior, id);
}


::CORBA::Boolean
_pof_BotControl::is_a(const char* id) const
{
  if( omni::ptrStrMatch(id, ::BotControl::_PD_repoId) )
    return 1;

  return 0;
}

const _pof_BotControl _the_pof_BotControl;

_impl_BotControl::~_impl_BotControl() {}


::CORBA::Boolean
_impl_BotControl::_dispatch(omniCallHandle& _handle)
{
  const char* op = _handle.operation_name();

  if( omni::strMatch(op, "init") ) {

    _0RL_cd_1473fd27e4f46097_00000000 _call_desc(_0RL_lcfn_1473fd27e4f46097_10000000, "init", 5, 1);

    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "getSpeed") ) {

    _0RL_cd_1473fd27e4f46097_20000000 _call_desc(_0RL_lcfn_1473fd27e4f46097_30000000, "getSpeed", 9, 1);

    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "setSpeed") ) {

    _0RL_cd_1473fd27e4f46097_40000000 _call_desc(_0RL_lcfn_1473fd27e4f46097_50000000, "setSpeed", 9, 1);

    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "getSteering") ) {

    _0RL_cd_1473fd27e4f46097_20000000 _call_desc(_0RL_lcfn_1473fd27e4f46097_60000000, "getSteering", 12, 1);

    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "setSteering") ) {

    _0RL_cd_1473fd27e4f46097_40000000 _call_desc(_0RL_lcfn_1473fd27e4f46097_70000000, "setSteering", 12, 1);

    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "getImageSensor") ) {

    _0RL_cd_1473fd27e4f46097_80000000 _call_desc(_0RL_lcfn_1473fd27e4f46097_90000000, "getImageSensor", 15, 1);

    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "getImageSensorDims") ) {

    _0RL_cd_1473fd27e4f46097_a0000000 _call_desc(_0RL_lcfn_1473fd27e4f46097_b0000000, "getImageSensorDims", 19, 1);

    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "getSensorValue") ) {

    _0RL_cd_1473fd27e4f46097_c0000000 _call_desc(_0RL_lcfn_1473fd27e4f46097_d0000000, "getSensorValue", 15, 1);

    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "motorsOff") ) {

    _0RL_cd_1473fd27e4f46097_e0000000 _call_desc(_0RL_lcfn_1473fd27e4f46097_f0000000, "motorsOff", 10, 1);

    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "setMotor") ) {

    _0RL_cd_1473fd27e4f46097_01000000 _call_desc(_0RL_lcfn_1473fd27e4f46097_11000000, "setMotor", 9, 1);

    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "sendRawCmd") ) {

    _0RL_cd_1473fd27e4f46097_21000000 _call_desc(_0RL_lcfn_1473fd27e4f46097_31000000, "sendRawCmd", 11, 1);

    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "setOIMode") ) {

    _0RL_cd_1473fd27e4f46097_e0000000 _call_desc(_0RL_lcfn_1473fd27e4f46097_41000000, "setOIMode", 10, 1);

    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "playSong") ) {

    _0RL_cd_1473fd27e4f46097_e0000000 _call_desc(_0RL_lcfn_1473fd27e4f46097_51000000, "playSong", 9, 1);

    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "dock") ) {

    _0RL_cd_1473fd27e4f46097_00000000 _call_desc(_0RL_lcfn_1473fd27e4f46097_61000000, "dock", 5, 1);

    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "shutdown") ) {

    _0RL_cd_1473fd27e4f46097_00000000 _call_desc(_0RL_lcfn_1473fd27e4f46097_71000000, "shutdown", 9, 1);

    _handle.upcall(this,_call_desc);
    return 1;
  }


  return 0;
}

void*
_impl_BotControl::_ptrToInterface(const char* id)
{
  if( id == ::BotControl::_PD_repoId )
    return (::_impl_BotControl*) this;

  if( id == ::CORBA::Object::_PD_repoId )
    return (void*) 1;

  if( omni::strMatch(id, ::BotControl::_PD_repoId) )
    return (::_impl_BotControl*) this;

  if( omni::strMatch(id, ::CORBA::Object::_PD_repoId) )
    return (void*) 1;
  return 0;
}

const char*
_impl_BotControl::_mostDerivedRepoId()
{
  return ::BotControl::_PD_repoId;
}

POA_BotControl::~POA_BotControl() {}

