// This file is generated by omniidl (C++ backend)- omniORB_4_1. Do not edit.
#ifndef __EchoImageServer_hh__
#define __EchoImageServer_hh__

#ifndef __CORBA_H_EXTERNAL_GUARD__
#include <omniORB4/CORBA.h>
#endif

#ifndef  USE_stub_in_nt_dll
# define USE_stub_in_nt_dll_NOT_DEFINED_EchoImageServer
#endif
#ifndef  USE_core_stub_in_nt_dll
# define USE_core_stub_in_nt_dll_NOT_DEFINED_EchoImageServer
#endif
#ifndef  USE_dyn_stub_in_nt_dll
# define USE_dyn_stub_in_nt_dll_NOT_DEFINED_EchoImageServer
#endif



#ifndef __ImageOrb_hh_EXTERNAL_GUARD__
#define __ImageOrb_hh_EXTERNAL_GUARD__
#include "Corba/ImageOrbSK.hh"
#endif



#ifdef USE_stub_in_nt_dll
# ifndef USE_core_stub_in_nt_dll
#  define USE_core_stub_in_nt_dll
# endif
# ifndef USE_dyn_stub_in_nt_dll
#  define USE_dyn_stub_in_nt_dll
# endif
#endif

#ifdef _core_attr
# error "A local CPP macro _core_attr has already been defined."
#else
# ifdef  USE_core_stub_in_nt_dll
#  define _core_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _core_attr
# endif
#endif

#ifdef _dyn_attr
# error "A local CPP macro _dyn_attr has already been defined."
#else
# ifdef  USE_dyn_stub_in_nt_dll
#  define _dyn_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _dyn_attr
# endif
#endif





#ifndef __EchoImageServer__
#define __EchoImageServer__

class EchoImageServer;
class _objref_EchoImageServer;
class _impl_EchoImageServer;

typedef _objref_EchoImageServer* EchoImageServer_ptr;
typedef EchoImageServer_ptr EchoImageServerRef;

class EchoImageServer_Helper {
public:
  typedef EchoImageServer_ptr _ptr_type;

  static _ptr_type _nil();
  static _CORBA_Boolean is_nil(_ptr_type);
  static void release(_ptr_type);
  static void duplicate(_ptr_type);
  static void marshalObjRef(_ptr_type, cdrStream&);
  static _ptr_type unmarshalObjRef(cdrStream&);
};

typedef _CORBA_ObjRef_Var<_objref_EchoImageServer, EchoImageServer_Helper> EchoImageServer_var;
typedef _CORBA_ObjRef_OUT_arg<_objref_EchoImageServer,EchoImageServer_Helper > EchoImageServer_out;

#endif

// interface EchoImageServer
class EchoImageServer {
public:
  // Declarations for this interface type.
  typedef EchoImageServer_ptr _ptr_type;
  typedef EchoImageServer_var _var_type;

  static _ptr_type _duplicate(_ptr_type);
  static _ptr_type _narrow(::CORBA::Object_ptr);
  static _ptr_type _unchecked_narrow(::CORBA::Object_ptr);

  static _ptr_type _nil();

  static inline void _marshalObjRef(_ptr_type, cdrStream&);

  static inline _ptr_type _unmarshalObjRef(cdrStream& s) {
    omniObjRef* o = omniObjRef::_unMarshal(_PD_repoId,s);
    if (o)
      return (_ptr_type) o->_ptrToObjRef(_PD_repoId);
    else
      return _nil();
  }

  static _core_attr const char* _PD_repoId;

  // Other IDL defined within this scope.

};

class _objref_EchoImageServer :
  public virtual ::CORBA::Object,
  public virtual omniObjRef
{
public:
  ImageOrb* echo(const ImageOrb& img);
  void shutdown();

  inline _objref_EchoImageServer()  { _PR_setobj(0); }  // nil
  _objref_EchoImageServer(omniIOR*, omniIdentity*);

protected:
  virtual ~_objref_EchoImageServer();


private:
  virtual void* _ptrToObjRef(const char*);

  _objref_EchoImageServer(const _objref_EchoImageServer&);
  _objref_EchoImageServer& operator = (const _objref_EchoImageServer&);
  // not implemented

  friend class EchoImageServer;
};

class _pof_EchoImageServer : public _OMNI_NS(proxyObjectFactory) {
public:
  inline _pof_EchoImageServer() : _OMNI_NS(proxyObjectFactory)(EchoImageServer::_PD_repoId) {}
  virtual ~_pof_EchoImageServer();

  virtual omniObjRef* newObjRef(omniIOR*,omniIdentity*);
  virtual _CORBA_Boolean is_a(const char*) const;
};

class _impl_EchoImageServer :
  public virtual omniServant
{
public:
  virtual ~_impl_EchoImageServer();

  virtual ImageOrb* echo(const ImageOrb& img) = 0;
  virtual void shutdown() = 0;

public:  // Really protected, workaround for xlC
  virtual _CORBA_Boolean _dispatch(omniCallHandle&);

private:
  virtual void* _ptrToInterface(const char*);
  virtual const char* _mostDerivedRepoId();

};




class POA_EchoImageServer :
  public virtual _impl_EchoImageServer,
  public virtual ::PortableServer::ServantBase
{
public:
  virtual ~POA_EchoImageServer();

  inline ::EchoImageServer_ptr _this() {
    return (::EchoImageServer_ptr) _do_this(::EchoImageServer::_PD_repoId);
  }
};







#undef _core_attr
#undef _dyn_attr



inline void
EchoImageServer::_marshalObjRef(::EchoImageServer_ptr obj, cdrStream& s) {
  omniObjRef::_marshal(obj->_PR_getobj(),s);
}




#ifdef   USE_stub_in_nt_dll_NOT_DEFINED_EchoImageServer
# undef  USE_stub_in_nt_dll
# undef  USE_stub_in_nt_dll_NOT_DEFINED_EchoImageServer
#endif
#ifdef   USE_core_stub_in_nt_dll_NOT_DEFINED_EchoImageServer
# undef  USE_core_stub_in_nt_dll
# undef  USE_core_stub_in_nt_dll_NOT_DEFINED_EchoImageServer
#endif
#ifdef   USE_dyn_stub_in_nt_dll_NOT_DEFINED_EchoImageServer
# undef  USE_dyn_stub_in_nt_dll
# undef  USE_dyn_stub_in_nt_dll_NOT_DEFINED_EchoImageServer
#endif

#endif  // __EchoImageServer_hh__

