// This file is generated by omniidl (C++ backend)- omniORB_4_1. Do not edit.
#ifndef __SceneRecServer_hh__
#define __SceneRecServer_hh__

#ifndef __CORBA_H_EXTERNAL_GUARD__
#include <omniORB4/CORBA.h>
#endif

#ifndef  USE_stub_in_nt_dll
# define USE_stub_in_nt_dll_NOT_DEFINED_SceneRecServer
#endif
#ifndef  USE_core_stub_in_nt_dll
# define USE_core_stub_in_nt_dll_NOT_DEFINED_SceneRecServer
#endif
#ifndef  USE_dyn_stub_in_nt_dll
# define USE_dyn_stub_in_nt_dll_NOT_DEFINED_SceneRecServer
#endif



#ifndef __ImageOrb_hh_EXTERNAL_GUARD__
#define __ImageOrb_hh_EXTERNAL_GUARD__
#include "Corba/ImageOrbSK.hh"
#endif



#ifdef USE_stub_in_nt_dll
# ifndef USE_core_stub_in_nt_dll
#  define USE_core_stub_in_nt_dll
# endif
# ifndef USE_dyn_stub_in_nt_dll
#  define USE_dyn_stub_in_nt_dll
# endif
#endif

#ifdef _core_attr
# error "A local CPP macro _core_attr has already been defined."
#else
# ifdef  USE_core_stub_in_nt_dll
#  define _core_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _core_attr
# endif
#endif

#ifdef _dyn_attr
# error "A local CPP macro _dyn_attr has already been defined."
#else
# ifdef  USE_dyn_stub_in_nt_dll
#  define _dyn_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _dyn_attr
# endif
#endif





#ifndef __SceneRecServer__
#define __SceneRecServer__

class SceneRecServer;
class _objref_SceneRecServer;
class _impl_SceneRecServer;

typedef _objref_SceneRecServer* SceneRecServer_ptr;
typedef SceneRecServer_ptr SceneRecServerRef;

class SceneRecServer_Helper {
public:
  typedef SceneRecServer_ptr _ptr_type;

  static _ptr_type _nil();
  static _CORBA_Boolean is_nil(_ptr_type);
  static void release(_ptr_type);
  static void duplicate(_ptr_type);
  static void marshalObjRef(_ptr_type, cdrStream&);
  static _ptr_type unmarshalObjRef(cdrStream&);
};

typedef _CORBA_ObjRef_Var<_objref_SceneRecServer, SceneRecServer_Helper> SceneRecServer_var;
typedef _CORBA_ObjRef_OUT_arg<_objref_SceneRecServer,SceneRecServer_Helper > SceneRecServer_out;

#endif

// interface SceneRecServer
class SceneRecServer {
public:
  // Declarations for this interface type.
  typedef SceneRecServer_ptr _ptr_type;
  typedef SceneRecServer_var _var_type;

  static _ptr_type _duplicate(_ptr_type);
  static _ptr_type _narrow(::CORBA::Object_ptr);
  static _ptr_type _unchecked_narrow(::CORBA::Object_ptr);

  static _ptr_type _nil();

  static inline void _marshalObjRef(_ptr_type, cdrStream&);

  static inline _ptr_type _unmarshalObjRef(cdrStream& s) {
    omniObjRef* o = omniObjRef::_unMarshal(_PD_repoId,s);
    if (o)
      return (_ptr_type) o->_ptrToObjRef(_PD_repoId);
    else
      return _nil();
  }

  static _core_attr const char* _PD_repoId;

  // Other IDL defined within this scope.

};

class _objref_SceneRecServer :
  public virtual ::CORBA::Object,
  public virtual omniObjRef
{
public:
  void newInput(const ImageOrb& img);
  ::CORBA::Short outputReady();
  ::CORBA::Short getLandmarkLoc(Point2DOrb& loc);
  void trainFeature(const ImageOrb& img, const Point2DOrb& loc, const DimsOrb& window, ::CORBA::Short leg);
  void shutdown();

  inline _objref_SceneRecServer()  { _PR_setobj(0); }  // nil
  _objref_SceneRecServer(omniIOR*, omniIdentity*);

protected:
  virtual ~_objref_SceneRecServer();


private:
  virtual void* _ptrToObjRef(const char*);

  _objref_SceneRecServer(const _objref_SceneRecServer&);
  _objref_SceneRecServer& operator = (const _objref_SceneRecServer&);
  // not implemented

  friend class SceneRecServer;
};

class _pof_SceneRecServer : public _OMNI_NS(proxyObjectFactory) {
public:
  inline _pof_SceneRecServer() : _OMNI_NS(proxyObjectFactory)(SceneRecServer::_PD_repoId) {}
  virtual ~_pof_SceneRecServer();

  virtual omniObjRef* newObjRef(omniIOR*,omniIdentity*);
  virtual _CORBA_Boolean is_a(const char*) const;
};

class _impl_SceneRecServer :
  public virtual omniServant
{
public:
  virtual ~_impl_SceneRecServer();

  virtual void newInput(const ImageOrb& img) = 0;
  virtual ::CORBA::Short outputReady() = 0;
  virtual ::CORBA::Short getLandmarkLoc(Point2DOrb& loc) = 0;
  virtual void trainFeature(const ImageOrb& img, const Point2DOrb& loc, const DimsOrb& window, ::CORBA::Short leg) = 0;
  virtual void shutdown() = 0;

public:  // Really protected, workaround for xlC
  virtual _CORBA_Boolean _dispatch(omniCallHandle&);

private:
  virtual void* _ptrToInterface(const char*);
  virtual const char* _mostDerivedRepoId();

};




class POA_SceneRecServer :
  public virtual _impl_SceneRecServer,
  public virtual ::PortableServer::ServantBase
{
public:
  virtual ~POA_SceneRecServer();

  inline ::SceneRecServer_ptr _this() {
    return (::SceneRecServer_ptr) _do_this(::SceneRecServer::_PD_repoId);
  }
};







#undef _core_attr
#undef _dyn_attr



inline void
SceneRecServer::_marshalObjRef(::SceneRecServer_ptr obj, cdrStream& s) {
  omniObjRef::_marshal(obj->_PR_getobj(),s);
}




#ifdef   USE_stub_in_nt_dll_NOT_DEFINED_SceneRecServer
# undef  USE_stub_in_nt_dll
# undef  USE_stub_in_nt_dll_NOT_DEFINED_SceneRecServer
#endif
#ifdef   USE_core_stub_in_nt_dll_NOT_DEFINED_SceneRecServer
# undef  USE_core_stub_in_nt_dll
# undef  USE_core_stub_in_nt_dll_NOT_DEFINED_SceneRecServer
#endif
#ifdef   USE_dyn_stub_in_nt_dll_NOT_DEFINED_SceneRecServer
# undef  USE_dyn_stub_in_nt_dll
# undef  USE_dyn_stub_in_nt_dll_NOT_DEFINED_SceneRecServer
#endif

#endif  // __SceneRecServer_hh__

