[SAMPLE	FRAME	TFRAME	OLDFRAME	NEWFRAME	STIMNAME	V7	V8	V9	...
 FEATURE	FEATURENAME	MIN	MAX	AVG	STD	MINX	MINY	MAXX	MAXY	...
 V20	V21	C1	C2	C3	C4	C5	C6	C7	C8	CLASS ] = ...
 textread('combined.stats2.txt','%d %d %d %d %d %s %d %s %d %s %s %f %f %f %f %d %d %d %d %d %s %d %d %d %d %d %d %d %d %d');