// This file is generated by omniidl (C++ backend)- omniORB_4_1. Do not edit.
#ifndef __CMap_hh__
#define __CMap_hh__

#ifndef __CORBA_H_EXTERNAL_GUARD__
#include <omniORB4/CORBA.h>
#endif

#ifndef  USE_stub_in_nt_dll
# define USE_stub_in_nt_dll_NOT_DEFINED_CMap
#endif
#ifndef  USE_core_stub_in_nt_dll
# define USE_core_stub_in_nt_dll_NOT_DEFINED_CMap
#endif
#ifndef  USE_dyn_stub_in_nt_dll
# define USE_dyn_stub_in_nt_dll_NOT_DEFINED_CMap
#endif



#ifndef __ImageOrb_hh_EXTERNAL_GUARD__
#define __ImageOrb_hh_EXTERNAL_GUARD__
#include "Corba/ImageOrbSK.hh"
#endif



#ifdef USE_stub_in_nt_dll
# ifndef USE_core_stub_in_nt_dll
#  define USE_core_stub_in_nt_dll
# endif
# ifndef USE_dyn_stub_in_nt_dll
#  define USE_dyn_stub_in_nt_dll
# endif
#endif

#ifdef _core_attr
# error "A local CPP macro _core_attr has already been defined."
#else
# ifdef  USE_core_stub_in_nt_dll
#  define _core_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _core_attr
# endif
#endif

#ifdef _dyn_attr
# error "A local CPP macro _dyn_attr has already been defined."
#else
# ifdef  USE_dyn_stub_in_nt_dll
#  define _dyn_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _dyn_attr
# endif
#endif





#ifndef __CMap__
#define __CMap__

class CMap;
class _objref_CMap;
class _impl_CMap;

typedef _objref_CMap* CMap_ptr;
typedef CMap_ptr CMapRef;

class CMap_Helper {
public:
  typedef CMap_ptr _ptr_type;

  static _ptr_type _nil();
  static _CORBA_Boolean is_nil(_ptr_type);
  static void release(_ptr_type);
  static void duplicate(_ptr_type);
  static void marshalObjRef(_ptr_type, cdrStream&);
  static _ptr_type unmarshalObjRef(cdrStream&);
};

typedef _CORBA_ObjRef_Var<_objref_CMap, CMap_Helper> CMap_var;
typedef _CORBA_ObjRef_OUT_arg<_objref_CMap,CMap_Helper > CMap_out;

#endif

// interface CMap
class CMap {
public:
  // Declarations for this interface type.
  typedef CMap_ptr _ptr_type;
  typedef CMap_var _var_type;

  static _ptr_type _duplicate(_ptr_type);
  static _ptr_type _narrow(::CORBA::Object_ptr);
  static _ptr_type _unchecked_narrow(::CORBA::Object_ptr);

  static _ptr_type _nil();

  static inline void _marshalObjRef(_ptr_type, cdrStream&);

  static inline _ptr_type _unmarshalObjRef(cdrStream& s) {
    omniObjRef* o = omniObjRef::_unMarshal(_PD_repoId,s);
    if (o)
      return (_ptr_type) o->_ptrToObjRef(_PD_repoId);
    else
      return _nil();
  }

  static _core_attr const char* _PD_repoId;

  // Other IDL defined within this scope.

};

class _objref_CMap :
  public virtual ::CORBA::Object,
  public virtual omniObjRef
{
public:
  ImageOrb* computeCMAP(const ImageOrb& img, ::CORBA::Short ptyp, ::CORBA::Float ori, ::CORBA::Float coeff);
  ImageOrb* computeCMAP2(const ImageOrb& img1, const ImageOrb& img2, ::CORBA::Short ptyp, ::CORBA::Float ori, ::CORBA::Float coeff);
  ImageOrb* computeFlickerCMAP(const ImageOrb& img, ::CORBA::Short ptyp, ::CORBA::Float ori, ::CORBA::Float coeff);
  void shutdown();

  inline _objref_CMap()  { _PR_setobj(0); }  // nil
  _objref_CMap(omniIOR*, omniIdentity*);

protected:
  virtual ~_objref_CMap();


private:
  virtual void* _ptrToObjRef(const char*);

  _objref_CMap(const _objref_CMap&);
  _objref_CMap& operator = (const _objref_CMap&);
  // not implemented

  friend class CMap;
};

class _pof_CMap : public _OMNI_NS(proxyObjectFactory) {
public:
  inline _pof_CMap() : _OMNI_NS(proxyObjectFactory)(CMap::_PD_repoId) {}
  virtual ~_pof_CMap();

  virtual omniObjRef* newObjRef(omniIOR*,omniIdentity*);
  virtual _CORBA_Boolean is_a(const char*) const;
};

class _impl_CMap :
  public virtual omniServant
{
public:
  virtual ~_impl_CMap();

  virtual ImageOrb* computeCMAP(const ImageOrb& img, ::CORBA::Short ptyp, ::CORBA::Float ori, ::CORBA::Float coeff) = 0;
  virtual ImageOrb* computeCMAP2(const ImageOrb& img1, const ImageOrb& img2, ::CORBA::Short ptyp, ::CORBA::Float ori, ::CORBA::Float coeff) = 0;
  virtual ImageOrb* computeFlickerCMAP(const ImageOrb& img, ::CORBA::Short ptyp, ::CORBA::Float ori, ::CORBA::Float coeff) = 0;
  virtual void shutdown() = 0;

public:  // Really protected, workaround for xlC
  virtual _CORBA_Boolean _dispatch(omniCallHandle&);

private:
  virtual void* _ptrToInterface(const char*);
  virtual const char* _mostDerivedRepoId();

};




class POA_CMap :
  public virtual _impl_CMap,
  public virtual ::PortableServer::ServantBase
{
public:
  virtual ~POA_CMap();

  inline ::CMap_ptr _this() {
    return (::CMap_ptr) _do_this(::CMap::_PD_repoId);
  }
};







#undef _core_attr
#undef _dyn_attr



inline void
CMap::_marshalObjRef(::CMap_ptr obj, cdrStream& s) {
  omniObjRef::_marshal(obj->_PR_getobj(),s);
}




#ifdef   USE_stub_in_nt_dll_NOT_DEFINED_CMap
# undef  USE_stub_in_nt_dll
# undef  USE_stub_in_nt_dll_NOT_DEFINED_CMap
#endif
#ifdef   USE_core_stub_in_nt_dll_NOT_DEFINED_CMap
# undef  USE_core_stub_in_nt_dll
# undef  USE_core_stub_in_nt_dll_NOT_DEFINED_CMap
#endif
#ifdef   USE_dyn_stub_in_nt_dll_NOT_DEFINED_CMap
# undef  USE_dyn_stub_in_nt_dll
# undef  USE_dyn_stub_in_nt_dll_NOT_DEFINED_CMap
#endif

#endif  // __CMap_hh__

