// This file is generated by omniidl (C++ backend)- omniORB_4_1. Do not edit.

#include "CMapSK.hh"
#include <omniORB4/IOP_S.h>
#include <omniORB4/IOP_C.h>
#include <omniORB4/callDescriptor.h>
#include <omniORB4/callHandle.h>
#include <omniORB4/objTracker.h>


OMNI_USING_NAMESPACE(omni)

static const char* _0RL_library_version = omniORB_4_1;



CMap_ptr CMap_Helper::_nil() {
  return ::CMap::_nil();
}

::CORBA::Boolean CMap_Helper::is_nil(::CMap_ptr p) {
  return ::CORBA::is_nil(p);

}

void CMap_Helper::release(::CMap_ptr p) {
  ::CORBA::release(p);
}

void CMap_Helper::marshalObjRef(::CMap_ptr obj, cdrStream& s) {
  ::CMap::_marshalObjRef(obj, s);
}

CMap_ptr CMap_Helper::unmarshalObjRef(cdrStream& s) {
  return ::CMap::_unmarshalObjRef(s);
}

void CMap_Helper::duplicate(::CMap_ptr obj) {
  if( obj && !obj->_NP_is_nil() )  omni::duplicateObjRef(obj);
}

CMap_ptr
CMap::_duplicate(::CMap_ptr obj)
{
  if( obj && !obj->_NP_is_nil() )  omni::duplicateObjRef(obj);
  return obj;
}

CMap_ptr
CMap::_narrow(::CORBA::Object_ptr obj)
{
  if( !obj || obj->_NP_is_nil() || obj->_NP_is_pseudo() ) return _nil();
  _ptr_type e = (_ptr_type) obj->_PR_getobj()->_realNarrow(_PD_repoId);
  return e ? e : _nil();
}


CMap_ptr
CMap::_unchecked_narrow(::CORBA::Object_ptr obj)
{
  if( !obj || obj->_NP_is_nil() || obj->_NP_is_pseudo() ) return _nil();
  _ptr_type e = (_ptr_type) obj->_PR_getobj()->_uncheckedNarrow(_PD_repoId);
  return e ? e : _nil();
}

CMap_ptr
CMap::_nil()
{
#ifdef OMNI_UNLOADABLE_STUBS
  static _objref_CMap _the_nil_obj;
  return &_the_nil_obj;
#else
  static _objref_CMap* _the_nil_ptr = 0;
  if( !_the_nil_ptr ) {
    omni::nilRefLock().lock();
    if( !_the_nil_ptr ) {
      _the_nil_ptr = new _objref_CMap;
      registerNilCorbaObject(_the_nil_ptr);
    }
    omni::nilRefLock().unlock();
  }
  return _the_nil_ptr;
#endif
}

const char* CMap::_PD_repoId = "IDL:CMap:1.0";


_objref_CMap::~_objref_CMap() {

}


_objref_CMap::_objref_CMap(omniIOR* ior, omniIdentity* id) :
   omniObjRef(::CMap::_PD_repoId, ior, id, 1)


{
  _PR_setobj(this);
}

void*
_objref_CMap::_ptrToObjRef(const char* id)
{
  if( id == ::CMap::_PD_repoId )
    return (::CMap_ptr) this;

  if( id == ::CORBA::Object::_PD_repoId )
    return (::CORBA::Object_ptr) this;

  if( omni::strMatch(id, ::CMap::_PD_repoId) )
    return (::CMap_ptr) this;

  if( omni::strMatch(id, ::CORBA::Object::_PD_repoId) )
    return (::CORBA::Object_ptr) this;

  return 0;
}

// Proxy call descriptor class. Mangled signature:
//  _cImageOrb_i_cImageOrb_i_cshort_i_cfloat_i_cfloat
class _0RL_cd_12c42ade728de8dd_00000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_12c42ade728de8dd_00000000(LocalCallFn lcfn,const char* op_,size_t oplen,_CORBA_Boolean upcall=0):
     omniCallDescriptor(lcfn, op_, oplen, 0, 0, 0, upcall)
  {

  }

  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);


  ImageOrb_var arg_0_;
  const ImageOrb* arg_0;
  ::CORBA::Short arg_1;
  ::CORBA::Float arg_2;
  ::CORBA::Float arg_3;
  ImageOrb_var result;
};

void _0RL_cd_12c42ade728de8dd_00000000::marshalArguments(cdrStream& _n)
{
  (const ImageOrb&) *arg_0 >>= _n;
  arg_1 >>= _n;
  arg_2 >>= _n;
  arg_3 >>= _n;

}

void _0RL_cd_12c42ade728de8dd_00000000::unmarshalArguments(cdrStream& _n)
{
  arg_0_ = new ImageOrb;
  (ImageOrb&)arg_0_ <<= _n;
  arg_0 = &arg_0_.in();
  (::CORBA::Short&)arg_1 <<= _n;
  (::CORBA::Float&)arg_2 <<= _n;
  (::CORBA::Float&)arg_3 <<= _n;

}

void _0RL_cd_12c42ade728de8dd_00000000::marshalReturnedValues(cdrStream& _n)
{
  (const ImageOrb&) result >>= _n;

}

void _0RL_cd_12c42ade728de8dd_00000000::unmarshalReturnedValues(cdrStream& _n)
{
  result = new ImageOrb;
  (ImageOrb&)result <<= _n;

}

// Local call call-back function.
static void
_0RL_lcfn_12c42ade728de8dd_10000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_12c42ade728de8dd_00000000* tcd = (_0RL_cd_12c42ade728de8dd_00000000*)cd;
  _impl_CMap* impl = (_impl_CMap*) svnt->_ptrToInterface(CMap::_PD_repoId);
  tcd->result = impl->computeCMAP(*tcd->arg_0, tcd->arg_1, tcd->arg_2, tcd->arg_3);


}

ImageOrb* _objref_CMap::computeCMAP(const ImageOrb& img, ::CORBA::Short ptyp, ::CORBA::Float ori, ::CORBA::Float coeff)
{
  _0RL_cd_12c42ade728de8dd_00000000 _call_desc(_0RL_lcfn_12c42ade728de8dd_10000000, "computeCMAP", 12);
  _call_desc.arg_0 = &(ImageOrb&) img;
  _call_desc.arg_1 = ptyp;
  _call_desc.arg_2 = ori;
  _call_desc.arg_3 = coeff;

  _invoke(_call_desc);
  return _call_desc.result._retn();


}
// Proxy call descriptor class. Mangled signature:
//  _cImageOrb_i_cImageOrb_i_cImageOrb_i_cshort_i_cfloat_i_cfloat
class _0RL_cd_12c42ade728de8dd_20000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_12c42ade728de8dd_20000000(LocalCallFn lcfn,const char* op_,size_t oplen,_CORBA_Boolean upcall=0):
     omniCallDescriptor(lcfn, op_, oplen, 0, 0, 0, upcall)
  {

  }

  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);


  ImageOrb_var arg_0_;
  const ImageOrb* arg_0;
  ImageOrb_var arg_1_;
  const ImageOrb* arg_1;
  ::CORBA::Short arg_2;
  ::CORBA::Float arg_3;
  ::CORBA::Float arg_4;
  ImageOrb_var result;
};

void _0RL_cd_12c42ade728de8dd_20000000::marshalArguments(cdrStream& _n)
{
  (const ImageOrb&) *arg_0 >>= _n;
  (const ImageOrb&) *arg_1 >>= _n;
  arg_2 >>= _n;
  arg_3 >>= _n;
  arg_4 >>= _n;

}

void _0RL_cd_12c42ade728de8dd_20000000::unmarshalArguments(cdrStream& _n)
{
  arg_0_ = new ImageOrb;
  (ImageOrb&)arg_0_ <<= _n;
  arg_0 = &arg_0_.in();
  arg_1_ = new ImageOrb;
  (ImageOrb&)arg_1_ <<= _n;
  arg_1 = &arg_1_.in();
  (::CORBA::Short&)arg_2 <<= _n;
  (::CORBA::Float&)arg_3 <<= _n;
  (::CORBA::Float&)arg_4 <<= _n;

}

void _0RL_cd_12c42ade728de8dd_20000000::marshalReturnedValues(cdrStream& _n)
{
  (const ImageOrb&) result >>= _n;

}

void _0RL_cd_12c42ade728de8dd_20000000::unmarshalReturnedValues(cdrStream& _n)
{
  result = new ImageOrb;
  (ImageOrb&)result <<= _n;

}

// Local call call-back function.
static void
_0RL_lcfn_12c42ade728de8dd_30000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_12c42ade728de8dd_20000000* tcd = (_0RL_cd_12c42ade728de8dd_20000000*)cd;
  _impl_CMap* impl = (_impl_CMap*) svnt->_ptrToInterface(CMap::_PD_repoId);
  tcd->result = impl->computeCMAP2(*tcd->arg_0, *tcd->arg_1, tcd->arg_2, tcd->arg_3, tcd->arg_4);


}

ImageOrb* _objref_CMap::computeCMAP2(const ImageOrb& img1, const ImageOrb& img2, ::CORBA::Short ptyp, ::CORBA::Float ori, ::CORBA::Float coeff)
{
  _0RL_cd_12c42ade728de8dd_20000000 _call_desc(_0RL_lcfn_12c42ade728de8dd_30000000, "computeCMAP2", 13);
  _call_desc.arg_0 = &(ImageOrb&) img1;
  _call_desc.arg_1 = &(ImageOrb&) img2;
  _call_desc.arg_2 = ptyp;
  _call_desc.arg_3 = ori;
  _call_desc.arg_4 = coeff;

  _invoke(_call_desc);
  return _call_desc.result._retn();


}
// Local call call-back function.
static void
_0RL_lcfn_12c42ade728de8dd_40000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_12c42ade728de8dd_00000000* tcd = (_0RL_cd_12c42ade728de8dd_00000000*)cd;
  _impl_CMap* impl = (_impl_CMap*) svnt->_ptrToInterface(CMap::_PD_repoId);
  tcd->result = impl->computeFlickerCMAP(*tcd->arg_0, tcd->arg_1, tcd->arg_2, tcd->arg_3);


}

ImageOrb* _objref_CMap::computeFlickerCMAP(const ImageOrb& img, ::CORBA::Short ptyp, ::CORBA::Float ori, ::CORBA::Float coeff)
{
  _0RL_cd_12c42ade728de8dd_00000000 _call_desc(_0RL_lcfn_12c42ade728de8dd_40000000, "computeFlickerCMAP", 19);
  _call_desc.arg_0 = &(ImageOrb&) img;
  _call_desc.arg_1 = ptyp;
  _call_desc.arg_2 = ori;
  _call_desc.arg_3 = coeff;

  _invoke(_call_desc);
  return _call_desc.result._retn();


}
// Proxy call descriptor class. Mangled signature:
//  void
class _0RL_cd_12c42ade728de8dd_50000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_12c42ade728de8dd_50000000(LocalCallFn lcfn,const char* op_,size_t oplen,_CORBA_Boolean upcall=0):
     omniCallDescriptor(lcfn, op_, oplen, 0, 0, 0, upcall)
  {

  }





};

// Local call call-back function.
static void
_0RL_lcfn_12c42ade728de8dd_60000000(omniCallDescriptor*, omniServant* svnt)
{

  _impl_CMap* impl = (_impl_CMap*) svnt->_ptrToInterface(CMap::_PD_repoId);
  impl->shutdown();


}

void _objref_CMap::shutdown()
{
  _0RL_cd_12c42ade728de8dd_50000000 _call_desc(_0RL_lcfn_12c42ade728de8dd_60000000, "shutdown", 9);


  _invoke(_call_desc);



}
_pof_CMap::~_pof_CMap() {}


omniObjRef*
_pof_CMap::newObjRef(omniIOR* ior, omniIdentity* id)
{
  return new ::_objref_CMap(ior, id);
}


::CORBA::Boolean
_pof_CMap::is_a(const char* id) const
{
  if( omni::ptrStrMatch(id, ::CMap::_PD_repoId) )
    return 1;

  return 0;
}

const _pof_CMap _the_pof_CMap;

_impl_CMap::~_impl_CMap() {}


::CORBA::Boolean
_impl_CMap::_dispatch(omniCallHandle& _handle)
{
  const char* op = _handle.operation_name();

  if( omni::strMatch(op, "computeCMAP") ) {

    _0RL_cd_12c42ade728de8dd_00000000 _call_desc(_0RL_lcfn_12c42ade728de8dd_10000000, "computeCMAP", 12, 1);

    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "computeCMAP2") ) {

    _0RL_cd_12c42ade728de8dd_20000000 _call_desc(_0RL_lcfn_12c42ade728de8dd_30000000, "computeCMAP2", 13, 1);

    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "computeFlickerCMAP") ) {

    _0RL_cd_12c42ade728de8dd_00000000 _call_desc(_0RL_lcfn_12c42ade728de8dd_40000000, "computeFlickerCMAP", 19, 1);

    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "shutdown") ) {

    _0RL_cd_12c42ade728de8dd_50000000 _call_desc(_0RL_lcfn_12c42ade728de8dd_60000000, "shutdown", 9, 1);

    _handle.upcall(this,_call_desc);
    return 1;
  }


  return 0;
}

void*
_impl_CMap::_ptrToInterface(const char* id)
{
  if( id == ::CMap::_PD_repoId )
    return (::_impl_CMap*) this;

  if( id == ::CORBA::Object::_PD_repoId )
    return (void*) 1;

  if( omni::strMatch(id, ::CMap::_PD_repoId) )
    return (::_impl_CMap*) this;

  if( omni::strMatch(id, ::CORBA::Object::_PD_repoId) )
    return (void*) 1;
  return 0;
}

const char*
_impl_CMap::_mostDerivedRepoId()
{
  return ::CMap::_PD_repoId;
}

POA_CMap::~POA_CMap() {}

