#!/bin/sh 

# Auto generated by linear_classify_build_process_em.m 
# Created: 07-Jun-2009 : 20.42.33.6265
# Do not edit this file directly 

nodes="icore icore icore icore icore icore icore icore icore icore icore icore icore icore icore icore icore icore icore icore icore icore icore icore icore icore icore icore icore icore icore icore "

/lab/mundhenk/linear-classifier/script/beoqueue.pl -n "$nodes" /lab/mundhenk/linear-classifier/script/process_rsvp.pl /lab/tmpib/u/nathan/newSequences/TransMask/stim??_???

#FOOTER