// This file is generated by omniidl (C++ backend)- omniORB_4_1. Do not edit.

#include "ImageOrbSK.hh"
#include <omniORB4/IOP_S.h>
#include <omniORB4/IOP_C.h>
#include <omniORB4/callDescriptor.h>
#include <omniORB4/callHandle.h>
#include <omniORB4/objTracker.h>


OMNI_USING_NAMESPACE(omni)

static const char* _0RL_library_version = omniORB_4_1;



void
ImageOrb::operator>>= (cdrStream &_n) const
{
  width >>= _n;
  height >>= _n;
  pix_size >>= _n;
  (const _CORBA_Unbounded_Sequence_Octet&) data >>= _n;

}

void
ImageOrb::operator<<= (cdrStream &_n)
{
  (::CORBA::Short&)width <<= _n;
  (::CORBA::Short&)height <<= _n;
  (::CORBA::Short&)pix_size <<= _n;
  (_CORBA_Unbounded_Sequence_Octet&)data <<= _n;

}

void
Point2DOrb::operator>>= (cdrStream &_n) const
{
  i >>= _n;
  j >>= _n;

}

void
Point2DOrb::operator<<= (cdrStream &_n)
{
  (::CORBA::Short&)i <<= _n;
  (::CORBA::Short&)j <<= _n;

}

void
DimsOrb::operator>>= (cdrStream &_n) const
{
  ww >>= _n;
  hh >>= _n;

}

void
DimsOrb::operator<<= (cdrStream &_n)
{
  (::CORBA::Short&)ww <<= _n;
  (::CORBA::Short&)hh <<= _n;

}

